version: "3.8"

services:
  postgres:
    image: postgres
    container_name: demo-postgres
    ports:
      - 5437:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo_usr
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: demo_db
volumes:
  postgres-data: